name: Generate Changelog

on:
  push:
    branches:
      - main

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Generate Changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          output_file: 'CHANGELOG.md'
          version: auto

      - name: Commit Changelog
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git add CHANGELOG.md
          git commit -m 'chore: update changelog'
          git push